name: TempBuild
version: '${version}'
main: pl.flezy.tempbuild.TempBuild
api-version: '1.19'
authors: [ Flezy ]
website: flezy.pl
depend: [WorldGuard]
commands:
    tempbuild:
        description: Main command for TempBuild plugin
        aliases: [tb]
        permission: tempbuild.command
permissions:
  tempbuild.command:
    default: op
    description: Allows to use tempbuild commands
    children:
      tempbuild.command.reload: true